### ISSUE TITLE
Let's set up a chat room

### ISSUE THREAD

**Issue by sgrif** [sgrif/diesel#111]
I'd like to have a public room for users, and a private room for contributors. IRC is generally out, as I'd like to have history (and not require going to a separate bot website to browse it). Slack is basically out for the same reason, as they limit the history on their free tier and don't offer free plans for OSS. I'm thinking maybe Gitter? Does anybody have a better option?

**Comment by mfpiccolo** [comment]
I have only used Gitter once very briefly but it looks legit enough to me.

**Comment by mcasper** [comment]
Most of my experience is with Campfire/Slack, but Gitter looks cool. Is HipChat still a thing?

**Comment by mfpiccolo** [comment]
I use hipchat, slack and flowdock.  Flowdock is by far my favorite but I am not sure about its guarantee of history.

**Comment by sgrif** [comment]
A lot of folks on twitter recommended gitter, and it looks like the best option ATM. I've set up a public room [here](https://gitter.im/sgrif/diesel?utm_source=share-link&utm_medium=link&utm_campaign=share-link). If you're a committer to the project, you've been added to a private room as well.
