### ISSUE TITLE
Add `diesel setup`

### ISSUE THREAD

**Issue by sgrif** [sgrif/diesel#115]
This should do the following:

- Look for a migrations dir. If it doesn't exist, create one in the same directory as `Cargo.toml` (maybe with a `.gitkeep` file so it's clear to the user that it's there if they want to move it later)
- Try to connect to `DATABASE_URL` if that env var is set (or if the `--database-url=` option was set, and the database doesn't exist, attempt to create it by connecting to the same URL with the database unspecified.
- Runs migrations if `__diesel_schema_migrations` doesn't already exist

**Comment by mcasper** [comment]
Should this also run any existing and pending migrations?

**Comment by sgrif** [comment]
Good point. I think it definitely makes sense for it to run migrations as a "I just cloned this app and want to get up and running" case. I'm not sure if it should just run pending migrations in general though, or if it should only run migrations if the `__diesel_schema_migrations` table didn't already exist. I'm open to arguments either way.

**Comment by mcasper** [comment]
I would err on the side of only running migrations if `__diesel_schema_migrations` didn't previously exist, as the use case in my mind was the 'I just cloned and want to get set up' scenario. If it always ran migrations I think it would just become a replacement for `diesel migration run`

**Comment by sgrif** [comment]
Yup, that's my thoughts as well. I've updated the original issue to include that as a prerequisite.

**Comment by pseudomuto** [comment]
Just browsing around here...did #126 close this?
