### ISSUE TITLE
Library build failing on windows

### ISSUE THREAD

**Issue by Virviil** [sgrif/diesel#121]
I'm trying to use diesel in project, developing in windows, pgsql is installed, C compilers probably not.

So my code is
```Rust
#[macro_use]
extern crate diesel;

fn main() {
    println!("Hello, world!");
}
```

With cargo:
```Toml
[dependencies]

diesel = "*"
```

And after 
```Sh
cargo build
```
i get this error:
https://gist.github.com/Virviil/79d816aab58822dd9461

**Comment by sgrif** [comment]
It looks like `pg_config.exe` isn't on your `PATH`. How did you install postgres on your machine? Can you make sure that executable is on your path and try again?

**Comment by Virviil** [comment]
I have installed it by the "official" way frm here: http://www.enterprisedb.com/products-services-training/pgdownload#windows
...\PostgreSQL\9.5\bin realy was not in my PATH.

After adding problem is not solved.

**Comment by sgrif** [comment]
Can you give the output of `where pg_config.exe` and also the output of `pg_config --libdir`?

**Comment by sgrif** [comment]
I've set up appveyor to confirm I didn't have anything funky setup locally. The only step required to get it to build was `SET PATH=%PATH%;C:\Program Files\PostgreSQL\9.4\bin` (note: Make sure you run `cargo clean` after setting that if it wasn't set before). I'm going to close this issue, as the library does appear to build on Windows just fine.

I'm happy to help you figure out the issue with your setup though, feel free to continue to comment.

**Comment by Virviil** [comment]
Yes, `cargo clean` solved the problem. Mb you previous post should be somehow added to readme or faq, i didn't found anything about PATH, and in windows world it's probably not so obvious as in nix.
