### ISSUE TITLE
Windows: note: ld: cannot find -lpq

### ISSUE THREAD

**Issue by Ciantic** [sgrif/diesel#135]
I tried with this:

```
#[macro_use]
extern crate diesel;
fn main() {
    println!("Hello world!");
}
```

The compilation fails with `note: ld: cannot find -lpq`

I downloaded PostgreSQL (portable) and set LD_LIBRARY_PATH environment variable, but it didn't help. I wonder should I set the library path some other way?

**edit** Also pg_config is in the PATH and it prints out the right directory.

**Comment by mcasper** [comment]
Have you tried running `cargo clean && cargo build`? A lot of the time cargo just needs to rebuild the package from scratch in order to pick up new link paths

**Comment by Ciantic** [comment]
Hmm, now it gives a longer error:

note: ld: skipping incompatible C:/Copies/.../PgSQL/lib/libpq.dll when searching for -lpq
ld: skipping incompatible C:/Copies/.../PgSQL/lib/libpq.dll when searching for -lpq
ld: cannot find -lpq

**Comment by mcasper** [comment]
That usually means that you've installed an incompatible version of the library (32bit vs 64bit, or for the wrong platform).

Can you confirm that you have the correct bit version installed?

**Comment by Ciantic** [comment]
Yes I also suspected this from the error message. It seems to be incorrect version (32 bit), if I could only find portable 64bit version to try...

But I think the cargo clean && cargo build solved the first issue so perhaps you can close this.

**Comment by Ciantic** [comment]
Note for future reference:

I found the 64 bit binary zip, which is portable already: http://www.postgresql.org/download/windows/ (note the small zip archive link at the end)

**Comment by bakasmarius** [comment]
The only thing that helped me was running this:
`SET PQ_LIB_DIR="C:\Program Files\PostgreSQL\13\lib"`
