### ISSUE TITLE
Latest diesel_codegen on crates.io requires syntex 0.25.*, while README says 0.26.*

### ISSUE THREAD

**Issue by Drakulix** [sgrif/diesel#138]
Basically what the title says. Crates.io version of diesel_codegen still requires syntex 0.25.* although the Readme clearly suggests to use ^0.26.0.
Git Repo seems to use 0.26.0 already, but was not pushed.

**Comment by sgrif** [comment]
The README on master documents the code on master. You can find the older versions on the tag for that version. The latest released is at https://github.com/sgrif/diesel/tree/v0.4.1

**Comment by Drakulix** [comment]
I would argue, that master then should also track master in the README:
```diesel_codegen = { git = "https://github.com/sgrif/diesel" }```

This way is confusing and unintuitive, although understandable, as the obvious example is broken.

**Comment by sgrif** [comment]
We usually try to keep master correct for the upcoming release, as it's
difficult as maintainers to keep track of all of the things that we would
need to change when we actually make the release. I understand your
frustration, but usually these sorts of cases are rare and minor. The
difficulty of avoiding it as a maintainer would be more difficult. If you'd
like to put a note in the readme, with a link to the latest released
version, I would accept that PR.

On Tue, Jan 26, 2016 at 6:38 PM, Victor Brekenfeld <notifications@github.com
> wrote:

> I would argue, that master then should also track master in the README:
> diesel_codegen = { git = "https://github.com/sgrif/diesel" }
>
> This way is confusing and unintuitive, although understandable, as the
> obvious example is broken.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sgrif/diesel/issues/138#issuecomment-175294245>.
>



-- 

Thanks,
Sean Griffin
