### ISSUE TITLE
Support dotenv for CLI

### ISSUE THREAD

**Issue by mcasper** [sgrif/diesel#147]
Right now you have to either have to set the DATABASE_URL environment variable, or pass the `--database-url` flag to the CLI. I think that most people these days are familiar and comfortable with dotenv, and probably have a `.env` in their project root. We should support and look for a `.env` file as well in the CLI, rather than requiring these users to copy and paste their connection url every time.

If we like this, I'll move forward with it this afternoon as well

**Comment by sgrif** [comment]
I'm fine with this, as long as we don't require `.env` to be set.

**Comment by mcasper** [comment]
Resolved by #163
