### ISSUE TITLE
[SQLite] Running our test suite spams the console with migration messages

### ISSUE THREAD

**Issue by sgrif** [sgrif/diesel#156]
### Note: PRs addressing this issue should target the `diesel-sqlite-support` branch, not `master`.

When we establish a new SQLite connection in our tests, we immediately run the pending migrations. This spams the console. I have no clue why these aren't being swallowed.

**Comment by mfpiccolo** [comment]
I have a feeling this is linked to https://github.com/rust-lang/rust/issues/12309

**Comment by sgrif** [comment]
Fixed by b25be2f
