### ISSUE TITLE
Name it!

### ISSUE THREAD

**Issue by sgrif** [sgrif/diesel#16]
I'm not pushing to crates.io without a name

**Comment by samphippen** [comment]
ActiveDiscord

**Comment by sgrif** [comment]
"Diesel" came to mind as an idea tonight.

**Comment by samphippen** [comment]
toofr: that one orm for rust.

**Comment by samphippen** [comment]
conveyorm

**Comment by r00k** [comment]
flibbets

**Comment by r00k** [comment]
smecker

**Comment by r00k** [comment]
dingbat

**Comment by r00k** [comment]
leper

**Comment by derekprior** [comment]
Storm (portmanteau of ruST and ORM)

**Comment by killercup** [comment]
As Rust was named after [the fungus](https://en.wikipedia.org/wiki/Rust_(fungus)), I think an appropriate name would be a fungus whose name contains "orm" :smile:

**Comment by derekprior** [comment]
I was trying to riff off the theme of correctness, went to its synonym "exactitude", and came up with "Exacta", which is the name of a bet in horse racing where you predict the first two horses in the correct order.

**Comment by sgrif** [comment]
Fixed by https://github.com/sgrif/diesel/commit/c8127d408f759faa056503014cd00e92479215e0. Diesel has stuck in my head as something easy to remember, and not already too overloaded in the tech space.
