### ISSUE TITLE
Make sure we still compile on Windows

### ISSUE THREAD

**Issue by sgrif** [sgrif/diesel#160]
I need to set up Appveyor for master, I will do that tomorrow. Since we've added new C deps, we need to verify that this still works on Windows given a reasonable installation.

**Comment by chriskrycho** [comment]
What exactly constitutes a "reasonable installation"? I've got Windows VMs set up for other reasons, would be happy to test it and see what pops out, if anything.

**Comment by sgrif** [comment]
Excellent question. I've not tried installing SQLite support on my Windows laptop, so I'm not sure how to qualify it for that, but the way I'd describe it for postgres is "Having installed PG from the links on their websites, and made sure `C:\Program Files\PostgreSQL\{version}\bin` is on the `%PATH%` (The second half being non-obvious, but unfortunately required).

**Comment by chriskrycho** [comment]
I'll give it a whirl sometime tomorrow; at the very least I should be able to report what's broken out of the gate as a totally-new user.

**Comment by sgrif** [comment]
Thanks. I'll probably merge #152 around lunch tomorrow once I have time to address stuff in the morning (I'm in UTC-7 if you want to get specific). I'll try to get Appveyor set up in the morning, too if you want to tackle getting SQLite working for that (they don't offer SQLite as a "service" and I'm not sure how well things like chocolatey work on that service)

**Comment by chriskrycho** [comment]
If I get the time, I’ll be happy to! (No promises; every time I make a promise in OSS I break it and am sad.)

**Comment by sgrif** [comment]
Hah, no pressure. <3

**Comment by sgrif** [comment]
The CLI tests fail against SQLite due to some contention over file locks (/cc @mcasper), but other than that everything is still fine on Windows.

**Comment by chriskrycho** [comment]
Huzzah! (Sorry I couldn’t help. But still: huzzah!)

**Comment by mcasper** [comment]
I think we're going to have to move to single threaded integration tests for the CLI anyways, so that should get cleared up soon.

**Comment by sgrif** [comment]
Our integration tests shouldn't need to be single threaded. ;)
