### ISSUE TITLE
`diesel setup` should give some indication that it created the migrations dir in its output

### ISSUE THREAD

**Issue by sgrif** [sgrif/diesel#177]
Right now it only says that it created the database. The terminal output should indicate that the migrations directory was created as well.

**Comment by mcasper** [comment]
@sgrif It already does

```
$ diesel setup
Created migrations/ directory at: /Users/mattcasper/code/home/test/migrations
Creating database: my_db
```

**Comment by sgrif** [comment]
Strange it wasn't doing that for me.

**Comment by mcasper** [comment]
https://github.com/sgrif/diesel/blob/master/diesel_cli/src/main.rs#L216
