### ISSUE TITLE
Question: Is it feasible to add non-SQL backends to Diesel? 

### ISSUE THREAD

**Issue by stephanbuys** [sgrif/diesel#198]
Hi,

I'm a Rust novice, ORM n00b, but I've been wondering about support from rust for Elasticsearch as a backend, would it be feasible to add an Elasticsearch backend to diesel, or am I thinking along the wrong lines?

(Love the work btw, SQLite is a _big_ deal, congrats!)

**Comment by sgrif** [comment]
In theory it should be possible, yes. However our API isn't really designed for that use case.
