### ISSUE TITLE
cargo install diesel_cli does not work if you haven't configured sqlite

### ISSUE THREAD

**Issue by Shiney** [sgrif/diesel#205]
If you haven't installed sqlite  then (on windows) the out of the box `cargo install diesel_cli ` will not work, due to not finidng the SQLITE3_LIB_DIR. 

I'm not sure if this matters but it means that if you are just targeting PostGres you have to install an additional dependency.

**Comment by sgrif** [comment]
I've released version 0.5.1 to address this. You can install with `cargo install diesel_cli --no-default-features --features postgres` now.

**Comment by Shiney** [comment]
Thanks
