### ISSUE TITLE
Error connecting to SQLite database

### ISSUE THREAD

**Issue by zamith** [sgrif/diesel#208]
I have this rust program that uses diesel, but fails when running with `'Error connection to "/Users/zamith/Library/Application Support/ActionAlly/action_ally.db": BadConnection("unable to open database file")'`:

```rust
extern crate rusty_ally;
extern crate diesel;

use self::rusty_ally::*;
use self::diesel::prelude::*;

fn main() {
    let connection = establish_connection();
}
```

This is strange, because accessing the same DB in Ruby works just fine:

```ruby
require "sqlite3"
require "dotenv"
Dotenv.load

db = SQLite3::Database.new ENV["DATABASE_URL"]

db.execute("select * from tasks limit 10") do |row|
  p row
end
```

Am I doing anything wrong? Is this even an issue with Diesel or with `libsqlite3-sys`?

**Comment by sgrif** [comment]
Can you give some steps to reproduce? Do you have write access to that directory? (Also does that directory exist?)

**Comment by zamith** [comment]
Even if I copy the database to the project's folder it's the same thing. I even tried creating a new database with `sqlite3 test.db`, change the `DATABASE_URL` to be `./test.db`, and ran the ruby and rust scripts again.

The result for ruby was an error because there was no table, on diesel it complained with the "unable to open database file" again. 

There's probably something I'm doing wrong in the rust code. I've pushed it [here](https://github.com/zamith/rusty_ally).

**Comment by zamith** [comment]
I get the same error if I remove the `test.db` file, and run `diesel setup`. I'm guessing this never happens on the tests because they all start the connection with `:memory:`.

**Comment by sgrif** [comment]
When I run the test suite against a file backed database with `RUST_TEST_THREADS=1`, the tests pass.

**Comment by zamith** [comment]
How can I run that? I can try that locally on my machine, and try to figure out what I'm doing wrong.

**Comment by sgrif** [comment]
https://gist.github.com/sgrif/1495ed44ac1d83cf2381, then set `DATABASE_URL` to something like `foo.sqlite3` and run the tests.

**Comment by sgrif** [comment]
I was able to replicate the error by attempting to run tests with a file in the `Application Support` directory.

**Comment by sgrif** [comment]
It appears that SQLite doesn't like paths with a space in them.

**Comment by zamith** [comment]
Hum... But even if I have the file on the same directory it is failing for me. I'm defining the path as `./foo.db` is that not the correct way?

**Comment by sgrif** [comment]
No, `foo.db` is the valid way, not `./foo.db`. It looks like dotenv on Rust doesn't handle any type of quoting or escaping. If you're using that, make sure that the `DATABASE_URL` line is set to:

```
DATABASE_URL=/Users/zamith/Library/Application Support/ActionAlly/action_ally.db
```

and not

```
DATABASE_URL="/Users/zamith/Library/Application Support/ActionAlly/action_ally.db"
```

or

```
DATABASE_URL=/Users/zamith/Library/Application\ Support/ActionAlly/action_ally.db
```

Based on your original post, I'm guessing that you have double quotes in your `.env` file.

**Comment by sgrif** [comment]
Also, doing `./foo.db` seems to work for me just fine. Not sure what's up with that.

**Comment by zamith** [comment]
That's correct. By removing the quotes it works. That's probably something that could be added to dotenv rust then.

Thanks and sorry for the trouble.

**Comment by sgrif** [comment]
I'm opening an issue there now. No worries, glad we got it resolved.
