### ISSUE TITLE
No syntax::ast::MetaItem_ in latest nightly

### ISSUE THREAD

**Issue by robojeb** [sgrif/diesel#218]
When compiling under the latest nightly diesel_codegen fails to compile because of renaming of types in the syntax::ast module. The error is:

`unresolved import 'syntax::ast::MetaItem_'. There is no 'MetaItem_' in 'syntax::ast'`

**Comment by barosl** [comment]
This is being fixed by #217, stay tuned!

**Comment by nokaa** [comment]
In case anyone else runs into this, a temporary fix is to clone the repository and copy the files in `diesel_codegen` to wherever cargo stores repositories. In my case, this was

`~/.multirust/toolchains/nightly/cargo/registry/src/github.com-xxxxxxxxxxxx/diesel_codegen-0.5.0`

**Comment by sgrif** [comment]
Or just point your cargo file at git?

**Comment by nokaa** [comment]
@sgrif I attempted to do that, but I was unsure what url to use for diesel_codegen. `https://github.com/sgrif/diesel/diesel_codegen` and `https://github.com/sgrif/diesel/tree/master/diesel_codegen` both failed to clone.

**Comment by sgrif** [comment]
Just point it at this repo.

**Comment by nokaa** [comment]
I didn't realise that was possible. Thank you! That is much easier.

**Comment by barosl** [comment]
You can also "override" some crates globally. Create a file named `~/.cargo/config`, and type this:

```
paths = [
    "/home/barosl/cloned-git-repos/diesel",
]
```

In this way you don't need to modify your `Cargo.toml`. But don't forget to remove the global path after the official version is released, otherwise you will use the outdated (cloned) version forever.
