### ISSUE TITLE
Diesel CLI's tests leave files laying around if tests fail

### ISSUE THREAD

**Issue by sgrif** [sgrif/diesel#222]
I'm working on some test failures that are occuring on Windows for Diesel CLI, and noticed that the tests in the database module aren't structured properly. They rely on calling a teardown function at the end, but that function is never called if the tests fail. These tests need to operate inside of a tempdir instead so that cleanup happens automatically. /cc @mcasper

**Comment by mcasper** [comment]
The tests that do that are probably obsolete now, or could be replaced by integration tests. I'll take a look tonight
