### ISSUE TITLE
Clarify relationship between general SQL types and backend-specific types

### ISSUE THREAD

**Issue by jimmycuadra** [sgrif/diesel#225]
The backend-specific types, e.g. `diesel::data_types`, contain some types that have seemingly identical counterparts in `diesel::types`. For example, there is both `diesel::types::Timestamp` and `diesel::data_types::PgTimestamp`. It's not clear why you would use one over the other. The docs for the backend-specific types say they are for cases where there is no native Rust type, and yet matching types appear in the generic `types` module anyway. Are both of them user-facing types? Is one an implementation detail that happens to be public? If you're using Postgres and the `table!` macro, which one do you use to declare a timestamp column? The docs should explain this. The module names `types` and `data_types` also have no semantic distinction which adds to the confusion.

**Comment by sgrif** [comment]
You would always use `types::Timestamp` in the table macro. `data_types::PgTimestamp` is something that can be deserialized from a column of that type.

**Comment by jimmycuadra** [comment]
Thanks! I can make a PR to add some docs explaining this. Is there anything else actionable here? Maybe a way to name the `types` and `data_types` module that's more clear?
