### ISSUE TITLE
implement `Send` for SqliteConnection

### ISSUE THREAD

**Issue by euclio** [sgrif/diesel#228]
Why is this not the case? It seems like it'd be ok given the reasons outlined in #190, but I admit that I'm not that familiar with the matter.

Use case: I'm working on a web application where I'd like to be able to share a SqliteConnection between multiple requests using a combination of [iron's](ironframework.io) [persistent](https://github.com/iron/persistent) crate and r2d2-diesel.

**Comment by sgrif** [comment]
> Why is this not the case?

Short version is that with SQLite, there's no cost to an additional connection. That said, I don't have a terribly strong opinion one way or another. If you want to open a PR for this with an argument laying out why implementing `Send` is beneficial over just establishing a new connection as you need it, I'd be open to it.

**Comment by euclio** [comment]
Right, but I think one use case would be for a `:memory:` database where you cannot create multiple connections to it.
