### ISSUE TITLE
PostGis types and functions

### ISSUE THREAD

**Issue by bfrog** [sgrif/diesel#232]
It would be great if diesel supports various postgis types and functions

**Comment by sgrif** [comment]
This isn't something I would want to put in the main Diesel crate, but it was designed to make it easy to add support for extensions like this. Here's an example crate which adds support for PG full text search. https://github.com/sgrif/diesel_full_text_search/blob/master/src/lib.rs

**Comment by dbrgn** [comment]
For the record, here's a crate that seems to support PostGIS geography types: https://github.com/Boscop/diesel-geography
