### ISSUE TITLE
#[insertable_into] fails with lifetimes other than 'a or 'insert

### ISSUE THREAD

**Issue by TimNN** [sgrif/diesel#246]
The following code fails to compile unless the `'b` lifetime is changed to `'a` or `'insert`:

```rust
#![feature(custom_attribute, plugin)]
#![plugin(diesel_codegen)]

#[macro_use]
extern crate diesel;

table! {
    foo {
        id -> Integer,
        s -> VarChar,
    }
}

#[insertable_into(foo)]
pub struct Bar<'b> {
    pub s: &'b str,
}
```

I believe that this code only works with `'a` because as far as I know lifetimes are exempt from macro hygiene.

**Comment by sgrif** [comment]
Fixed in 4771cb6b624ae4fbff42ed6115034b831591125c
