### ISSUE TITLE
Getting started guide link broken?

### ISSUE THREAD

**Issue by davidhewitt** [sgrif/diesel#254]
I was hoping to read the [getting started guide](http://diesel.rs/guides/getting-started), but it seems like the domain might have an incorrect DNS entry. Chrome gives me the following:

> This site can’t be reached
> diesel.rs’s server DNS address could not be found.
> ERR_NAME_NOT_RESOLVED

However, the [docs](docs.diesel.rs) (at docs.diesel.rs) work fine, so the domain exists...

Is there somewhere else I can find the getting started guide?

**Comment by sgrif** [comment]
Hm. Looks like I broke the website when setting up the docs subdomain... Let me see what I can do.

**Comment by sgrif** [comment]
I've fixed the DNS records. It might take up to an hour for the record to propagate.
