### ISSUE TITLE
Add some missing common functions

### ISSUE THREAD

**Issue by sgrif** [sgrif/diesel#37]
We have `max`. We don't have `min`. Or `avg`, `sum`, etc. We should add these. They should not use the `sql_function!` macro, as they need to accept more than one argument type. `min` should have the same bounds as `max`. Others might need new bounds. I'm fine with just naming the trait something like `CanBePassedToAvg` or something, if there's not a good generic name. If you ever need to find the types which can be passed to a function in postgres, just open up psql and run this query:

```sql
select typname from pg_type where oid in (select proargtypes::text::oid from pg_proc where proname = 'sum');
```

**Comment by tessgriffin** [comment]
Just to be clear, even though there's a PR that shows up here that says "Add sum function", we still don't have a sum function because @mfpiccolo is a lazy jerk.
