### ISSUE TITLE
Generate table by deriving Queriable

### ISSUE THREAD

**Issue by defyrlt** [sgrif/diesel#40]
In issue #36 I was trying to get example with `#[derive(Queriable)]` to work and one of the things that confused me is that you still have to make a `table!` call and hand-write all the column types.
Here I'm proposing to make `Queriable` smart enough to generate appropriate table stuff or even `table!` call so you won't have to do it manually. For some cases you might want to manually set the type of the column, e.g
```rust
#[derive(Queriable, Debug)]
pub struct User {
    #[column_type = Serial]
    id: i32,
    #[column_type = VarChar]
    name: String,
}
```
P.S @sgrif thanks for all the great work you've done! I'm very excited about query builder/ORM in Rust.

**Comment by sgrif** [comment]
I do not like the idea of generating a table from `Queriable`, as it implies too heavily that a struct has to be one to one with a database table, and puts too much schema information in the struct itself. I'd prefer a macro which generates the `table!` call for you based on the database schema at compile time.

**Comment by sgrif** [comment]
Forgot to reference this from the other PR. First pass at this is https://github.com/sgrif/diesel/pull/49 -- There will be an additional macro which loads table names from schema and calls that one automatically.
