### ISSUE TITLE
#[changeset_for] with postgresql arrays

### ISSUE THREAD

**Issue by scalexm** [sgrif/diesel#63]
While I can do this:
```rust
table! {
    foo {
        id -> Serial,
        bar -> Array<Integer>,
    }
}

#[derive(Queriable)]
struct Foo {
    bar: Vec<i32>,
}
```

I can't do that:
```rust
#[changeset_for(foo)]
struct Foo {
    bar: Vec<i32>,
}
```

Is there a way to achieve this?

**Comment by sgrif** [comment]
I've fixed the issue with `Vec<T>`, but there's a separate issue here when `#[changeset_for]` is used on a struct with a single field which is not yet fixed. See #66.
