### ISSUE TITLE
Incorrect spelling of Queriable trait name

### ISSUE THREAD

**Issue by sologub** [sgrif/diesel#71]
The correct name would be *Queryable*.

**Comment by mfpiccolo** [comment]
It does look like Queryable is the preferred spelling.  Google even gives a suggestion.
<img width="651" alt="screen shot 2015-12-28 at 7 36 07 am" src="https://cloud.githubusercontent.com/assets/3249825/12020908/0e0c3a9a-ad36-11e5-966c-a677fcac1ae7.png">
However, there are several references to Queriable as an acceptable alternate spelling.

**Comment by sologub** [comment]
I'd like to note that the Queryable name is used with a similar functionality in .NET LINQ, so the name difference may become a source of pain for .NET devs.  
But I understand that this is a breaking change, so please feel free to just close this issue if you consider it unimportant.

**Comment by sgrif** [comment]
Yup, this appears to be correct. We can add a type alias as `Queriable` to ease migration. Feel free to open a PR renaming.
