### ISSUE TITLE
Infer macros with CI

### ISSUE THREAD

**Issue by mcasper** [sgrif/diesel#84]
What's the recommended way of dealing with the `infer_*` macros and CIs? Say if you have

```
infer_table_from_schema!(dotenv!("DATABASE_URL"), "users");
```

You can create the database in a `before_script` with Travis, but the table still won't exist at compile time. You could obviously also create the table in the `before_script` section, but that feels like it would get onerous as your number of tables grows.

I realize there may be no easy way of dealing with this since it is a convenience compile-time check, just wanted to see if you had a nice way.

**Comment by sgrif** [comment]
`cargo install diesel_cli && diesel migration run` in `before_script` should make sure that they exist at compile time. You can also do `diesel::migrations::run_pending_migrations` from `build.rs`.

**Comment by mcasper** [comment]
Oh right, the migrations cli is out. Wonderful! Thank you
